version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://email_security_user:root@db:5432/email_security_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    volumes:
      - .:/app
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: email_security_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: email_security_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:
  postgres_data:

networks:
  app_network:
